---
title: "Coherence Simulation"
author: "Sophie Woodward"
date: '2023-05-17'
output: pdf_document
---

```{r}
library(tidyverse)
library(sp)
library("raster")
library("dplyr")
library("sf")
library("stringr")
library("ggplot2")
library(grid) 
library(pBrackets) 
library(gridExtra)
library("lme4")
```

## Import Synthetic Data
```{r}
study = read.csv('/Users/sophie/Documents/SpatialConf/Study_dataset_2010.csv')
adj = read.csv("/Users/sophie/Documents/SpatialConf/adjacency_matrix.csv", header = F) # created from spacebench script
```

# Plot exposure and confounder in US
```{r}
# Import geographies
us = map_data('state')

states = st_read("/Users/sophie/Documents/SpatialConf/tl_2010_us_county10/tl_2010_us_county10.shp")

study$FIPS = str_pad(study$FIPS, 5, pad = '0')
study_map = mutate(study, 
                   STATEFP10 = str_sub(FIPS, 1, 2),
                   COUNTYFP10 = str_sub(FIPS, 3, 5))

mapdat = left_join(states, study_map, by = c("STATEFP10", "COUNTYFP10"))

g1 = ggplot(mapdat) +
  xlim(-125, -65) + 
  ylim(25, 50) +
  geom_sf(aes(fill = qd_mean_pm25), color='grey', size = 0.005) +
  #  scale_fill_viridis_c(option="magma",begin=0.4)+
  # scale_fill_viridis_c(option="magma",begin=0,direction = -1, breaks = c(0,4,8,12,16,20))+
  scale_fill_gradient2(expression(paste("PM"[2.5])), 
                       low = "#1e90ff", 
                       mid = "#ffffba", 
                       high = "#8b0000", 
                       midpoint = 9,
                       breaks = c(0, 3, 6, 9, 12),
                       labels = c("0", "3", "6", "9", "12+"),
                       limits = c(0, 15),
                       na.value = "white") +
  # labs(title = expression(paste("Annual Average of PM"[2.5]," per ",mu,g/m^3," in 2000-2016"))) +
  theme_minimal() +
  theme(plot.title = element_text(size = 24 * 2,hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        line = element_blank(),
        axis.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal", 
        legend.text = element_text(angle = 60,  size = 20 * 2),
        legend.text.align = 0.75,
        legend.title = element_text(size = 24 * 2),
        legend.key.width = unit(150 * 2, "points"),
        panel.grid.major = element_line(colour = "transparent"))

png("county_pm.jpeg", height = 1024 * 0.6 * 2, width = 1024 * 2)
g1
dev.off()

g2 = ggplot(mapdat) +
  xlim(-125, -65) + 
  ylim(25, 50) +
  geom_sf(aes(fill = gmet_mean_tmmn), color='grey', size = 0.005) +
  #  scale_fill_viridis_c(option="magma",begin=0.4)+
  # scale_fill_viridis_c(option="magma",begin=0,direction = -1, breaks = c(0,4,8,12,16,20))+
  scale_fill_gradient2(expression('Gmet_mean_tmmn'), 
                       low = "#1e90ff", 
                       mid = "#ffffba", 
                       high = "#8b0000", 
                       midpoint = 280,
                       breaks = c(270, 275, 280, 285, 290),
                       labels = c("270", "275", "280", "285", "290"),
                       limits = c(265, 295),
                       na.value = "white") +
  theme_minimal() +
  theme(plot.title = element_text(size = 24 * 2,hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        line = element_blank(),
        axis.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal", 
        legend.text = element_text(angle = 60,  size = 20 * 2),
        legend.text.align = 0.75,
        legend.title = element_text(size = 24 * 2),
        legend.key.width = unit(150 * 2, "points"),
        panel.grid.major = element_line(colour = "transparent"))

png("county_mean_tmmn.jpeg", height = 1024 * 0.6 * 2, width = 1024 * 2)
g2
dev.off()
```

## Exposure and Confounder in the West
```{r}
west = which(study$region == 'WEST')
studysub = study[west,]
study_map = mutate(studysub, 
                   STATEFP10 = str_sub(FIPS, 1, 2),
                   COUNTYFP10 = str_sub(FIPS, 3, 5))

mapdata <- right_join(states, study_map, by = c("STATEFP10", "COUNTYFP10"))

g3 <- ggplot(mapdata) +
  xlim(-125, -65) + 
  ylim(25, 50) +
  geom_sf(aes(fill = qd_mean_pm25), color='grey', size = 0.005) +
  #  scale_fill_viridis_c(option="magma",begin=0.4)+
  # scale_fill_viridis_c(option="magma",begin=0,direction = -1, breaks = c(0,4,8,12,16,20))+
  scale_fill_gradient2(expression(paste("PM"[2.5])), 
                       low = "#1e90ff", 
                       mid = "#ffffba", 
                       high = "#8b0000", 
                       midpoint = 9,
                       breaks = c(0, 3, 6, 9, 12),
                       labels = c("0", "3", "6", "9", "12+"),
                       limits = c(0, 15),
                       na.value = "white") +
  # labs(title = expression(paste("Annual Average of PM"[2.5]," per ",mu,g/m^3," in 2000-2016"))) +
  theme_minimal() +
  theme(plot.title = element_text(size = 24 * 2,hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        line = element_blank(),
        axis.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal", 
        legend.text = element_text(angle = 60,  size = 20 * 2),
        legend.text.align = 0.75,
        legend.title = element_text(size = 24 * 2),
        legend.key.width = unit(150 * 2, "points"),
        panel.grid.major = element_line(colour = "transparent"))

png("pm_west.jpeg", height = 1024 * 0.6 * 2, width = 1024 * 2)
g3
dev.off()

g4 = ggplot(mapdata) +
  xlim(-125, -65) + 
  ylim(25, 50) +
  geom_sf(aes(fill = gmet_mean_tmmn), color='grey', size = 0.005) +
  #  scale_fill_viridis_c(option="magma",begin=0.4)+
  # scale_fill_viridis_c(option="magma",begin=0,direction = -1, breaks = c(0,4,8,12,16,20))+
  scale_fill_gradient2(expression('Gmet_mean_tmmn'), 
                       low = "#1e90ff", 
                       mid = "#ffffba", 
                       high = "#8b0000", 
                       midpoint = 280,
                       breaks = c(270, 275, 280, 285, 290),
                       labels = c("270", "275", "280", "285", "290"),
                       limits = c(265, 295),
                       na.value = "white") +
  theme_minimal() +
  theme(plot.title = element_text(size = 24 * 2,hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        line = element_blank(),
        axis.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal", 
        legend.text = element_text(angle = 60,  size = 20 * 2),
        legend.text.align = 0.75,
        legend.title = element_text(size = 24 * 2),
        legend.key.width = unit(150 * 2, "points"),
        panel.grid.major = element_line(colour = "transparent"))

png("mean_tmmn_west.jpeg", height = 1024 * 0.6 * 2, width = 1024 * 2)
g4
dev.off()
```

## Starting Simulation
```{r}
west = which(study$region == 'WEST')
studysub = study[west,]
adjsub = adj[west,west]

R     <- diag(rowSums(adjsub))-adjsub # precision of ICAR
E     <- eigen(R) # eigen component
G     <- E$vec
D     <- E$val

set.seed(22)
# Let X be qd_mean_pm25
X = studysub$qd_mean_pm25
Xscaled = scale(X) # make mean 0 sd 1
# Let Z be mean min temp?
Z = studysub$gmet_mean_tmmn
Zscaled = scale(Z) # make mean 0 sd 1
C = studysub[,c(4:12,14, 16, 17:22, 24:37)]  # 31 measured covariates (real data)
Cscaled = scale(C)

nsims = 100
corest <- c()
corsp <- c()
outXstar <- c()
outZstar <- c()
outCstar <- list()
for(sim in 1:nsims){ # code is very slow
  print(sim)
  # Perturb X, Z, C
  X_pert = rep(NA, length(Xscaled))
  Z_pert = rep(NA, length(Zscaled))
  C_pert = matrix(NA, nrow(Cscaled), ncol(Cscaled))
  for (j in 1:nrow(studysub)){
    neighbors = which(adjsub[j,] != 0)
    X_pert[j] = mean(Xscaled[neighbors]) + rnorm(1, 0, 0.2)
    Z_pert[j] = mean(Zscaled[neighbors]) + rnorm(1, 0, 0.1)
    C_pert[j,] = colMeans(Cscaled[neighbors,]) + rnorm(31, 0, 0.1)
  }
  # project all variables into the spectral domain using graph Fourier transform
  Xstar <- t(G)%*%X_pert
  Zstar <- t(G)%*%Z_pert
  Cstar <- t(G)%*%C_pert
  outXstar <- cbind(outXstar,Xstar)
  outZstar <- cbind(outZstar,Zstar)
  outCstar[[sim]] = Cstar
}

# Calculate spectral covariance and alpha
covest = unlist(lapply(1:length(X), function(i) {
  Cmat = matrix(unlist(lapply(outCstar, function(j) j[i,])), nrow = nsims, ncol = 31, byrow = T)
  covmat = cov(cbind(outZstar[i,], outXstar[i,], Cmat)) # cov
  return((covmat[1,2:(2+31)]%*%solve(covmat[2:(2+31),2:(2+31)]))[1]) # alphax
  }
  )
)

# Plot
plot(D, abs(covest),xlab='Eigenvalue',ylab="|Alpha(omega)|")
```

## Trying with local covariance method
```{r}
west = which(study$region == 'WEST')
studysub = study[west,]
adjsub = adj[west,west]

R     <- diag(rowSums(adjsub))-adjsub # precision of ICAR
E     <- eigen(R) # eigen component
G     <- E$vec
D     <- E$val

# Let X be qd_mean_pm25
X = studysub$qd_mean_pm25
Xscaled = scale(X) # make mean 0 sd 1
# Let Z be mean min temp?
Z = studysub$gmet_mean_tmmn
Zscaled = scale(Z) # make mean 0 sd 1
C = studysub[,c(4:12,14, 16, 17:22, 24:37)]  # 31 measured covariates (real data)
Cscaled = scale(C)
Xstar <- t(G)%*%Xscaled
Zstar <- t(G)%*%Zscaled
Cstar <- t(G)%*%Cscaled

# are entries in the vector close? 
k = 5
alphas = rep(NA, length(Xstar))
for (i in 1:length(Xstar)){
  window = seq(max(1, i-k), min(i+k, length(Xstar)), by = 1)
  #print(window)
  weights = exp(-abs(window-i))
  weights = weights/sum(weights)
  #print(weights)
  covmat = cov.wt(cbind(Zstar[window], Xstar[window], Cstar[window,]), 
                wt = weights)$cov
 alphas[i] = (covmat[1,2:(2+31)]%*%solve(covmat[2:(2+31),2:(2+31)], tol = 1e-23))[1] 
}

plot(D, abs(alphas),xlab='Eigenvalue',ylab="|Alpha(omega)|")

```





