---
title: "Decompositions"
author: "Sophie Woodward"
date: '2023-06-08'
output:
  pdf_document:
    fig_width: 6
    fig_height: 3
    toc: yes
geometry: margin=1cm
---

```{r, include = F}
source('funcs.R')
library(raster)
library(fields)

if (!file.exists('out.Rdata')){
  source('runsim.R') 
}
load('out.Rdata')
load('outsim.Rdata')
```

# Plot grid
```{r}
png("images/grid1.jpeg")
r <- raster(xmn = 0, xmx = 27, ymn = 0, ymx = 27, nrows = 3, ncols = 3)
r[] <- sample(1:9)
plot(r, legend = F)
dev.off()

png("images/grid2.jpeg")
r <- raster(xmn = 0, xmx = 27, ymn = 0, ymx = 27, nrows = 9, ncols = 9)
r[] <- sample(1:81)
plot(r, legend = F)
dev.off()

png("images/grid3.jpeg")
r <- raster(xmn = 0, xmx = 27, ymn = 0, ymx = 27, nrows = 27, ncols = 27)
r[] <- sample(1:729)
plot(r, legend = F)
dev.off()
```

# Plot eigenvectors by eigenvalue
```{r, eigenplots, cache = T, echo = F, message = F, results = 'hide', warning = F}
# extract eigen
R = diag(rowSums(outsim$A)) - outsim$A # graph laplacian 
E = eigen(R) # eigen component
D = E$val
G = E$vec
png("images/eigenR.jpeg", height = 700, width = 1200, res = 100)
par(mfrow = c(3,6))
  for (j in 1:18){
    ix = 40*(j-1)+1
    z = G[,ix]
    image.plot(x=1:27, y=1:27, z = matrix(z, nrow = 27,ncol = 27), 
               main = paste('lambda =', round(D[ix],2)), col = viridis(n = 20), 
               zlim = c(-0.10, 0.10))
    #dfr = rasterFromXYZ(cbind.data.frame(outsim$coord, z))    
    #image(dfr, main = paste('lambda =', round(D[ix],2)))
  }
dev.off()
png('images/histDsim.jpeg', height = 700, width = 700, res = 100)
hist(D, main = 'Histogram of Eigenvalues: Simulated Data', 
     xlab = 'eigenvalue', breaks = 20)
dev.off()
```

# Visualization of X and Z
```{r}
nest = nested_decomp_mats(outsim$groups)
X = outsim$X
Z = outsim$Z
X1 = nest$decomp_mats[[1]] %*% X
X2 = nest$decomp_mats[[2]] %*% X
X3 = nest$decomp_mats[[3]] %*% X
Z1 = nest$decomp_mats[[1]] %*% Z
Z2 = nest$decomp_mats[[2]] %*% Z
Z3 = nest$decomp_mats[[3]] %*% Z
png("images/XZ.jpeg", width = 1000, height = 600, res = 100)
par(mfrow = c(2,4))
image.plot(x=1:27, y=1:27, z = matrix(X1, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'X(1)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(X2, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'X(2)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(X3, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'X(3)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(X, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'X',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(Z1, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'Z(1)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(Z2, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'Z(2)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(Z3, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'Z(3)',
             xlab = '', ylab = '')
image.plot(x=1:27, y=1:27, z = matrix(Z, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = 'Z',
             xlab = '', ylab = '')
dev.off()

png(filename = 'images/XZhist.jpeg', width = 1000, height = 500)
par(mfrow = c(1,2))
hist(Z)
hist(X)
dev.off()
```

## Visualizations of X,Y,Z in the spectral domain
```{r}
# extract eigen
R = diag(rowSums(outsim$A)) - outsim$A # graph laplacian 
E = eigen(R) # eigen component
D = E$val
G = E$vec
n = 3
l = 3
Jks = list()
Bks = list()
num = n^(2*l-2)
zeroeig = which(apply(t(G), 1, function(x) length(unique(round(x,10)))) == 1)
for (i in 1:(n^2)){ 
  window = (num*(i-1) + 1):(num*i)
  window = setdiff(window, zeroeig)
  k = rep(0, n^(2*l))
  k[window] = 1
  Jks[[i]] = diag(k)
  Bks[[i]] = G %*% diag(k) %*% t(G)
}

png('images/spatial_Xstar.jpeg', width = 2000, height = 2000, res = 150)
par(mfrow = c(4,3))
# Plot spatial-spectral X
for (i in 1:length(Bks)){
  window = (num*(i-1) + 1):(num*i)
  window = setdiff(window, zeroeig)
  image.plot(x=1:27, y=1:27, z = matrix(Bks[[i]] %*% outsim$X, nrow = 27,ncol = 27), 
                 col = viridis(n = 20), zlim = c(-1.5,1.5),
             main = paste('avglambda =', round(mean(D[window]),2)),
             xlab = '', ylab = '')
}
# and plot original nested X
nest = nested_decomp_mats(outsim$groups)
for (j in 1:3){
  image.plot(x=1:27, y=1:27, z = matrix(nest$decomp_mats[[j]]%*%outsim$X, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = paste('X level', j), xlab = '', ylab = '')
}
dev.off()

png('images/spatial_Ystar.jpeg', width = 2000, height = 2000, res = 150)
par(mfrow = c(4,3))
for (i in 1:length(Bks)){
  window = (num*(i-1) + 1):(num*i)
  window = setdiff(window, zeroeig)
  image.plot(x=1:27, y=1:27, z = matrix(Bks[[i]] %*% outsim$Y, nrow = 27,ncol = 27), 
                 col = viridis(n = 20), zlim = c(-3,3),
             main = paste('avglambda =', round(mean(D[window]),2)))
}
# and plot original nested Y
nest = nested_decomp_mats(outsim$groups)
for (j in 1:3){
  image.plot(x=1:27, y=1:27, z = matrix(nest$decomp_mats[[j]]%*%outsim$Y, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = paste('Y level', j), xlab = '', ylab = '')
}
dev.off()

png('images/spatial_Zstar.jpeg', width = 2000, height = 2000, res = 150)
par(mfrow = c(4,3))
for (i in 1:length(Bks)){
  window = (num*(i-1) + 1):(num*i)
  window = setdiff(window, zeroeig)
  image.plot(x=1:27, y=1:27, z = matrix(Bks[[i]] %*% outsim$Z, nrow = 27,ncol = 27), 
                 col = viridis(n = 20), zlim = c(-1.5,1.5),
             main = paste('avglambda =', round(mean(D[window]),2)))
}
# and plot original nested Z
nest = nested_decomp_mats(outsim$groups)
for (j in 1:3){
  image.plot(x=1:27, y=1:27, z = matrix(nest$decomp_mats[[j]]%*%outsim$Z, nrow = 27,ncol = 27), 
                 col = viridis(n = 20),
             main = paste('Z level', j), xlab = '', ylab = '')
}
dev.off()
```

```{r, sim1, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/nesteddgm.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[1]]$nestedmat, spectralmat = out[[1]]$spectralmat, 
         D=D,
         mains = c('Nested: Ground Truth', 'Spectral: Estimation'))
dev.off()
```

```{r, sim3, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/spectraldgm1.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[3]]$nestedmat, spectralmat = out[[3]]$spectralmat, 
         D=D,
         mains = c('Nested: Estimation', 'Spectral: Ground Truth'))
dev.off()
```

```{r, sim4, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/spectraldgm2.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[4]]$nestedmat, spectralmat = out[[4]]$spectralmat, 
          D=D,
         mains = c('Nested: Estimation', 'Spectral: Ground Truth'))
dev.off()
```

# Simulation 3: Correlation by Spatial Scale

```{r, sim5, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/cornesteddgm.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[5]]$nestedmat, 
                     spectralmat = out[[5]]$spectralmat,
                      D=D,
                     ylab='Cor(X,Z)',
                     hline=0,
                     ylim=c(-1,1),
                     col='purple', 
         mains = c('Nested: Ground Truth', 'Spectral: Estimation'))
dev.off()
```

```{r, sim7, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/corspectraldgm.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[7]]$nestedmat, 
                  D=D,
                  spectralmat = out[[7]]$spectralmat,
                     ylab='Cor(X,Z)',
                     hline=0,
                     ylim=c(-1.1,1.1),
                     col='purple', 
         mains = c('Nested: Estimation', 'Spectral: Ground Truth'))
dev.off()
```

```{r}
png("images/corspectraldgm2.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[15]]$nestedmat, 
                       D=D,
                      spectralmat = out[[15]]$spectralmat,
                     ylab='Cor(X,Z)',
                     hline=0,
                     ylim=c(-1.1,1.1),
                     col='purple', 
         mains = c('Nested: Estimation', 'Spectral: Ground Truth'))
dev.off()
```


# Simulation 4: Local Confounding

```{r, sim9, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/localnested.jpeg", height = 600, width = 1300, res = 200)
plotfunc(nestedmat = out[[9]]$nestedmat, spectralmat = out[[9]]$spectralmat, 
         D=D,
         mains = c('Nested: Ground Truth', 'Spectral: Estimation'))
dev.off()
```


```{r, sim10, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/localspectral.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[10]]$nestedmat,
  spectralmat = out[[10]]$spectralmat,
  D=D,
  mains = c('Nested: Estimation', 'Spectral: Ground Truth')
)
dev.off()
```

# Simulation 5: Outcome Model with Interaction

```{r, sim11, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/interaction_nested.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[11]]$nestedmat,
  spectralmat = out[[11]]$spectralmat,
  D=D,
  ylim = c(-4, 4),
  mains = c('Nested: Ground Truth', 'Spectral: Estimation')
)
dev.off()
```

```{r, sim12, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/interaction_spectral.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[12]]$nestedmat,
  spectralmat = out[[12]]$spectralmat,
  D=D,
  ylim = c(-5, 5),
  mains = c('Nested: Estimation', 'Spectral: Ground Truth')
)
dev.off()
```

# Simulation 6: Nonlinear Outcome Model

```{r, sim13, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/quadratic_nested.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[13]]$nestedmats[, , 1],
  spectralmat = out[[13]]$spectralmats[, , 1],
  D=D,
  ylim = c(-2, 2),
  mains = c('Nested Linear: Ground Truth', 'Spectral Linear: Estimation')
)
dev.off()
```


```{r, sim131, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/quadratic_nested2.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[13]]$nestedmats[, , 2],
  spectralmat = out[[13]]$spectralmats[, , 2],
  D=D,
  ylim = c(-2, 2),
  hline = 1,
  mains = c('Nested Quadratic: Ground Truth', 'Spectral Quadratic: Estimation')
)
dev.off()
```

```{r, sim14, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/quadratic_spectral.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[14]]$nestedmats[, , 1],
  spectralmat = out[[14]]$spectralmats[, , 1],
  D=D,
  ylim = c(-2, 2),
  mains = c('Nested Linear: Estimation', 'Spectral Linear: Ground Truth')
)
dev.off()
```

```{r, sim141, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/quadratic_spectral2.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[14]]$nestedmats[, , 2],
  spectralmat = out[[14]]$spectralmats[, , 2],
  D=D,
  hline = 1,
  ylim = c(-2, 2),
  mains = c('Nested Quadratic: Estimation', 'Spectral Quadratic: Ground Truth')
)
dev.off()
```

# Real data sim
```{r, sim15, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/realsim1.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[16]]$nestedmat,
  spectralmat = out[[16]]$spectralmat,
  D=D,
  ylim = c(-2.5,2.5),
   nestlabels = c('Region', 'State', 'County'),
  mains = c('Nested: Ground Truth', 'Spectral: Estimation')
)
dev.off()
```

```{r, sim15, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/realsim2.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[17]]$nestedmat,
  spectralmat = out[[17]]$spectralmat,
  D=D,
  ylim = c(-1.5, 1.5),
   nestlabels = c('Region', 'State', 'County'),
  mains = c('Nested: Estimation', 'Spectral: Ground Truth')
)
dev.off()
```

```{r, sim15, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/realsim3.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[18]]$nestedmat,
  spectralmat = out[[18]]$spectralmat,
  D=D,
  ylim = c(-1, 1),
  nestlabels = c('Region', 'State', 'County'),
  hline = 0,
  ylab = 'correlation',
  mains = c('Nested: Ground Truth', 'Spectral: Estimation')
)
dev.off()
```

```{r, sim15, cache = T, echo = F, message = F, results = 'hide', warning = F}
png("images/realsim4.jpeg", height = 600, width = 1300, res = 200)
plotfunc(
  nestedmat = out[[19]]$nestedmat,
  spectralmat = out[[19]]$spectralmat,
  D=D,
  ylim = c(-1, 1),
  hline = 0,
  ylab = 'correlation',
 nestlabels = c('Region', 'State', 'County'),
 mains = c('Nested: Estimation', 'Spectral: Ground Truth')
)
dev.off()
```



