---
title: "Decompositions"
author: "Mauricio Tec"
date: '2023-06-08'
output:
    github_document:
        html_preview: false
---

```{r, warning=FALSE, message=FALSE}
source("funcs.R")
```

```{r}
# Create a group matrix
L <- 4
n <- 32
g <- matrix(0, nrow = n, ncol = L)
for (j in 1:(L - 1)) {
    g[, j] <- 1 + (0:(n - 1)) %/% (n %/% 2^j)
}
g[ ,L] <- 1:n
head(g, 16)
```

Obtain two lists. The first one contains the projection matrices $(P_j)_{j=1}^L$ and the second one contains the decomposition matrices $(A_j)_{j=1}^L$.

```{r}
res <- nested_decomp(g)
names(res)
```

Apply decoposition to some vector $x$.

```{r}
# example vector
x <- 1:n  # just for example and visualization

# orthogonal components
x_orth <- matrix(0, nrow = n, ncol = L)
x_averaged <- matrix(0, nrow = n, ncol = L)
for (j in 1:L) {
    x_averaged[, j] <- res$proj_mat[[j]] %*% x
    x_orth[, j] <- res$decomp_mat[[j]] %*% x
}
```

Verify that the averages are correct.

```{r}
head(x_averaged, 16)
```


Verify the orthogonality.

```{r}
cor(x_orth)
```


Verify the reconstruction.

```{r} 
rowSums(x_orth) == x
```
