#!/bin/bash
set -euo pipefail

# Usage: bash submit_jobs.sh [alpha] [run_label]
#   alpha:     basis-selection stopping-rule tuning parameter (default 1)
#   run_label: used to build a distinct results/output/error directory so
#              different alpha runs never share a results_dir (default
#              derived from alpha, e.g. "alpha1")
alpha="${1:-1}"
run_label="${2:-alpha${alpha}}"

base_dir="/n/home07/swoodward/instrumental_variables_simulation_aug25"
results_subdir="results_manuscript_cluster_1000reps_quadratic_${run_label}"
output_subdir="output_${run_label}"
error_subdir="error_${run_label}"

mkdir -p "${base_dir}/simulation/${output_subdir}" "${base_dir}/simulation/${error_subdir}" \
  "${base_dir}/simulation/${results_subdir}"

# Define arrays for options and methods
confounding_mechanisms=(1 2 3 4 5 6 7 8)
options=("linear" "nonlinear")
nsims=1000
n_cores=8
seed=20260825
core_fraction=0.9
# +spatialcoord IV variants and trueIV-spatialcoord dropped from the study;
# plain spatialcoord is kept. All 6 methods run for every alpha value (each
# alpha's results directory is fully self-contained), even though alpha only
# actually affects IV-TPS/IV-GraphLaplacian -- oracle/baseline/spatialcoord/
# trueIV results will be identical (same seed) across alpha runs.
methods="oracle,baseline,spatialcoord,trueIV,IV-TPS,IV-GraphLaplacian"
# New directory per run -- funcs.R appends new reps as extra
# columns onto existing output files if the file already exists, and the old
# 20-rep mechanism 4/8 data was generated by the pre-fix DGP (see
# compute_data_TPS_reversed / compute_data_GL_reversed), and the 1000-rep
# directory was generated under local_degree=1. Mixing any of these into the
# same files would silently corrupt results.
results_dir="${base_dir}/simulation/${results_subdir}/"

echo "Submitting alpha=${alpha} (run_label=${run_label}) into ${results_dir}"

# Loop through each combination and submit jobs
for cm in "${confounding_mechanisms[@]}"; do
  for option in "${options[@]}"; do
  sbatch --job-name="cm${cm}_${option}_${run_label}" \
      --output="${base_dir}/simulation/${output_subdir}/cm${cm}_${option}.out" \
      --error="${base_dir}/simulation/${error_subdir}/cm${cm}_${option}.err" \
      run_job.sh "$nsims" "$cm" "$option" "TRUE" "$n_cores" \
      "$results_dir" "$seed" "$methods" "$core_fraction" "$alpha"
  sleep 1 # pause to be kind to the scheduler
  done
done
