#!/bin/bash

base_dir="/n/home07/swoodward/instrumental_variables_simulation_aug25"
mkdir -p "${base_dir}/simulation/output" "${base_dir}/simulation/error" \
  "${base_dir}/simulation/results_manuscript_cluster_1000reps"

# Define arrays for options and methods
confounding_mechanisms=(1 2 3 4 5 6 7 8)
options=("linear" "nonlinear")
nsims=1000
n_cores=8
seed=20260825
core_fraction=0.9
# +spatialcoord IV variants and trueIV-spatialcoord dropped from the study;
# plain spatialcoord is kept.
methods="oracle,baseline,spatialcoord,trueIV,IV-TPS,IV-GraphLaplacian"
# New directory -- do not reuse results_manuscript_cluster_20reps/. funcs.R
# appends new reps as extra columns onto existing output files, and the old
# 20-rep mechanism 4/8 data was generated by the pre-fix DGP (see
# compute_data_TPS_reversed / compute_data_GL_reversed). Mixing old and new
# reps in the same file would silently corrupt the mechanism 4/8 results.
results_dir="${base_dir}/simulation/results_manuscript_cluster_1000reps/"

# Loop through each combination and submit jobs
for cm in "${confounding_mechanisms[@]}"; do
  for option in "${options[@]}"; do
  sbatch --job-name="cm${cm}_${option}" \
      --output="${base_dir}/simulation/output/cm${cm}_${option}.out" \
      --error="${base_dir}/simulation/error/cm${cm}_${option}.err" \
      run_job.sh "$nsims" "$cm" "$option" "TRUE" "$n_cores" \
      "$results_dir" "$seed" "$methods" "$core_fraction"
  sleep 1 # pause to be kind to the scheduler
  done
done